### ISSUE TITLE
[RESOURCE REQUEST] Vulkan in a nutshell

### ISSUE THREAD

**Issue by DethRaid** [GraphicsProgramming/resources#12]
### Do you have a preference for API or language used to discuss the topic?

Idk about your questions but https://liamhinzman.com/blog/vulkan-fundamentals seems really good and we should add it

**Comment by hYdos** [comment]
https://vulkan-tutorials.com

**Comment by hYdos** [comment]
wait wrong link this is it https://vulkan-tutorial.com/

**Comment by nickclark2016** [comment]
@hYdos that is already in there

**Comment by hYdos** [comment]
well you dont really need much more. it itself contains links to other things if i remember
