### ISSUE TITLE
Vulkan resources

### ISSUE THREAD

**Issue by Amani747** [GraphicsProgramming/resources#15]
Examples/Samples:
https://github.com/KhronosGroup/Vulkan-Samples

https://github.com/SaschaWillems/Vulkan

Performance theory:
https://zeux.io/2020/02/27/writing-an-efficient-vulkan-renderer/

https://developer.nvidia.com/blog/vulkan-dos-donts/

https://developer.nvidia.com/blog/best-practices-gpu-performance-events/

http://32ipi028l5q82yhj72224m8j.wpengine.netdna-cdn.com/wp-content/uploads/2016/03/VulkanFastPaths.pdf

**Comment by Amani747** [comment]
As well, maybe order the links as:
Spec,
Tutorial,
Samples,
Best practices,
Preformance,
ect

**Comment by deccer** [comment]
Can you please create a PR in the proper section and also provide a little description of the link - see existing links in index.html - Its just simple markdown.

If you happen to be on our discord server, just boop me when done.

**Comment by nickclark2016** [comment]
To follow up, I find that the expected ordering of links/resources varies between who you ask.  I'd like to keep it alphabetical, so even if it may not be the best order always, it's consistent and easy to follow.  Agree with @deccer, put in a PR if you have some time.

**Comment by nickclark2016** [comment]
Following up.  @Amani747 is this going to be worked by you, or does someone else need to pick this up?

**Comment by Amani747** [comment]
@nickclark2016 Sorry, It completely slipped my mind. I've made the changes and created a PR.
