### ISSUE TITLE
Awesome Ray Tracing

### ISSUE THREAD

**Issue by dannyfritz** [GraphicsProgramming/resources#4]
Awesome Ray Tracing

https://github.com/dannyfritz/awesome-ray-tracing

**Comment by nickclark2016** [comment]
The point of the repo is for community built resources, hosted at https://graphicsprogramming.github.io/resources.  You're more than welcome to create PRs for resources to be uploaded there, but for now, this issue is being closed for lack of constructiveness.

**Comment by dannyfritz** [comment]
Ah yeah. I misunderstood that. No worries. 👍
