### ISSUE TITLE
Site link

### ISSUE THREAD

**Issue by Bfgeshka** [GraphicsProgramming/resources#7]
Link to https://graphicsprogramming.github.io/resources/ is never mentioned anywhere while being the main focus. Repository header doesn'r have it, readme doesn't have it, your group description doesn't have it, discord welcome page doesn't have it.

**Comment by deccer** [comment]
Partially true, #community-resource-discussion has it, but you are completely right. we are working on it.

**Comment by CalebAdrianXYZ** [comment]
The website is now hosted at https://graphics-programming.org, a README should be added to reflect this.

**Comment by nickclark2016** [comment]
Stale issue. Closing.
