### ISSUE TITLE
Set Default Branch to gh-pages

### ISSUE THREAD

**Issue by cwfitzgerald** [GraphicsProgramming/resources#8]
Seems a bit silly to have master be the default if we're just going to use gh pages.

**Comment by deccer** [comment]
I agree, I was thinking of at least providing some README with links to the branches for all these various topics... branchnames are also a bit of a mess

**Comment by JPBotelho** [comment]
At least a link to the website would be great

**Comment by deccer** [comment]
Set default branch to `gh-pages`.
